### ISSUE TITLE
topk表达错误

### ISSUE THREAD

**Issue by wacodespace** [wmn7/ML_Practice#1]
看一下三维的
x = torch.tensor([
    [0.1, 0.2 ,0.5, 0.2],
    [0.4, 0.3, 0.2, 0.1],
    [0.1, 0.2, 0.5, 0.1],
])
我们可以看到第三维是dim=0, "行"是dim=1, 列是dim=2
print(x.shape)
### 这个张量是二维的，而且“行”是dim=0,列是dim=1

**Comment by wmn7** [comment]
~~想问一下是哪一个文件里的呢~~

已经修改. 也已经在原文中进行修改, [理解PyTorch中维度的概念](https://mathpretty.com/12065.html)
